/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author laispaivaportela
 */
import principal.Principal;
import model.Aluno;
import controller.ControleAluno;
import controller.SistemaUniversidade;
import static principal.Principal.CONTROLE_ALUNO;
import static principal.Principal.SISTEMA_UNIVERSIDADE;

public class FrmSistemaUniversidade extends javax.swing.JFrame {


   


    /**
     * Creates new form FrmSistemaUniversidade
     */
    public FrmSistemaUniversidade() {
        initComponents();
   
    }
   // public FrmSistemaUniversidade(int escolha){
        //this.escolha = escolha;
   // } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        jMenuItem1 = new javax.swing.JMenuItem();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar3 = new javax.swing.JMenuBar();
        mnuArquivo = new javax.swing.JMenu();
        itmCadastrarAluno = new javax.swing.JMenuItem();
        itmFichaAluno = new javax.swing.JMenuItem();
        itmGerenciarAluno = new javax.swing.JMenuItem();
        itmSair = new javax.swing.JMenuItem();
        mnuRelatorios = new javax.swing.JMenu();
        itmAlunos = new javax.swing.JMenuItem();
        mnuSobre = new javax.swing.JMenu();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        jLabel1.setText("jLabel1");

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\laisp_omzy4s1\\OneDrive\\Documentos\\NetBeansProjects\\SistemaUniversidade\\menu.png")); // NOI18N
        jLabel2.setMaximumSize(new java.awt.Dimension(1920, 1080));
        jLabel2.setMinimumSize(new java.awt.Dimension(300, 300));

        mnuArquivo.setText("Arquivo");
        mnuArquivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuArquivoActionPerformed(evt);
            }
        });

        itmCadastrarAluno.setText("Cadastrar Aluno");
        itmCadastrarAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmCadastrarAlunoActionPerformed(evt);
            }
        });
        mnuArquivo.add(itmCadastrarAluno);

        itmFichaAluno.setText("Ficha Aluno");
        itmFichaAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmFichaAlunoActionPerformed(evt);
            }
        });
        mnuArquivo.add(itmFichaAluno);

        itmGerenciarAluno.setText("Gerenciar Aluno");
        itmGerenciarAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmGerenciarAlunoActionPerformed(evt);
            }
        });
        mnuArquivo.add(itmGerenciarAluno);

        itmSair.setText("Sair");
        itmSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmSairActionPerformed(evt);
            }
        });
        mnuArquivo.add(itmSair);

        jMenuBar3.add(mnuArquivo);

        mnuRelatorios.setText("Relatorios");

        itmAlunos.setText("Alunos");
        itmAlunos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmAlunosActionPerformed(evt);
            }
        });
        mnuRelatorios.add(itmAlunos);

        jMenuBar3.add(mnuRelatorios);

        mnuSobre.setText("Sobre");
        jMenuBar3.add(mnuSobre);

        setJMenuBar(jMenuBar3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //manda qual ação deverá ser realizada (qual item dos menus foi escolhido) para o sistema
    private void itmGerenciarAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmGerenciarAlunoActionPerformed
        SISTEMA_UNIVERSIDADE.executarAcao(2);
    }//GEN-LAST:event_itmGerenciarAlunoActionPerformed

    private void itmCadastrarAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmCadastrarAlunoActionPerformed

        SISTEMA_UNIVERSIDADE.executarAcao(1);
    }//GEN-LAST:event_itmCadastrarAlunoActionPerformed

    private void mnuArquivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuArquivoActionPerformed
        //nadinha
    }//GEN-LAST:event_mnuArquivoActionPerformed

    private void itmFichaAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmFichaAlunoActionPerformed
        SISTEMA_UNIVERSIDADE.executarAcao(3);
    }//GEN-LAST:event_itmFichaAlunoActionPerformed

    private void itmSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmSairActionPerformed
        SISTEMA_UNIVERSIDADE.executarAcao(0);
    }//GEN-LAST:event_itmSairActionPerformed

    private void itmAlunosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmAlunosActionPerformed
        //posteriormente imprimirá relatório completo dos alunos matriculados
    }//GEN-LAST:event_itmAlunosActionPerformed

    
    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itmAlunos;
    private javax.swing.JMenuItem itmCadastrarAluno;
    private javax.swing.JMenuItem itmFichaAluno;
    private javax.swing.JMenuItem itmGerenciarAluno;
    private javax.swing.JMenuItem itmSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenu mnuArquivo;
    private javax.swing.JMenu mnuRelatorios;
    private javax.swing.JMenu mnuSobre;
    // End of variables declaration//GEN-END:variables
}
